services:
  shako:
    container_name: shako-linktree
    image: ttl.sh/shako-jaumoso:1h
    user: "1000:1000"
    ports:
#      - 9485:80
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=false

