services:
  shako:
    container_name: shako-linktree
    image: ghcr.io/jaumoso/shako:latest
    user: 1000:1000
    ports:
      - 9485:80
    restart: unless-stopped
    labels:
      - com.centurylinklabs.watchtower.enable=false
networks: {}
