services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WEBUI_PORT=8098
      - TORRENTING_PORT=6887
    volumes:
      - ./config:/config
      - /mnt/externaldisk0/media/default:/downloads
    ports:
      - 8098:8098
      - 6887:6887
      - 6887:6887/udp
    restart: unless-stopped
    networks:
      - jellyfin
#    network_mode: "container:gluetun" # Makes qBittorrent use VPN

networks:
  jellyfin:
    external: true
