services:
  scrutiny:
    image: ghcr.io/analogj/scrutiny:master-omnibus
    container_name: scrutiny
    restart: unless-stopped
    devices:
      - /dev/sdd
      - /dev/sda
      - /dev/nvme0
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN
    volumes:
      - /run/udev:/run/udev:ro
      - ./config:/config
      - ./scrutiny-config:/opt/scrutiny/config
      - ./influxdb:/opt/scrutiny/influxdb
    ports:
      - 8096:8086
      - 8090:8080
    tty: true
    stdin_open: true
    environment:
      #          - PUID=1000
      #          - PGID=1000
      - TZ=Europe/Madrid
      - SCRUTINY_COLLECTOR=true
networks: {}
