name: actualbudget
services:
  actual-server:
    restart: unless-stopped
    ports:
      - 5006:5006
    volumes:
      - /mnt/externaldisk0/actualbudget:/data
    container_name: actualbudget
    image: actualbudget/actual-server:latest
    environment:
      - ACTUAL_LOGIN_METHOD=password
networks: {}
