services:
  dash:
    image: mauricenino/dashdot:latest
    container_name: dash
    restart: unless-stopped
    privileged: true
    ports:
      - '3020:3001'
    volumes:
      - /:/mnt/host:ro
    networks:
      - npm
    environment:
      DASHDOT_ENABLE_CPU_TEMPS: 'true'
      DASHDOT_CPU_TEMPS_MODE: 'max'
      DASHDOT_SHOW_DASH_VERSION: 'true'
      DASHDOT_ALWAYS_SHOW_PERCENTAGES: 'true'

networks:
  npm:
    external: true
