services:
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest
    volumes:
      - /mnt/externaldisk0/backrest/data:/data
      - ./config:/config
      - ./rclone:/root/.config/rclone
      - /mnt/externaldisk0/backrest/cache:/cache
      - /mnt/externaldisk0/backrest/tmp:/tmp
      - /mnt/externaldisk0:/externaldisk0 # Mount local paths to backup
      - /mnt/externaldisk1:/externaldisk1
      - /home/jaumoso/selfhosted:/jaumoso/selfhosted
      - /home/jaumoso/unused:/jaumoso/unused
      - /home/jaumoso/scripts:/jaumoso/scripts
    #      - /path/to/local/repos:/repos     # Mount local repos (optional for remote storage)
    environment:
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      - TZ=Europe/Madrid
    ports:
      - 9898:9898
    restart: unless-stopped
networks: {}
