volumes:
  navidrome_data: null
services:
  navidrome:
    container_name: navidrome
    image: deluan/navidrome:latest
    restart: unless-stopped
    #read_only: true
    #user: 1000:1000
    ports:
      - 4533:4533
    volumes:
      - navidrome_data:/data
      - /mnt/externaldisk0/media/music:/music:ro
networks: {}
