version: '3.9'
services:
  web-check:
    container_name: web-check
    image: lissy93/web-check
    ports:
      - 3050:3000
    restart: unless-stopped
    environment:
        - PUID=1000
        - PGID=1000
    labels:
      - homepage.group=Herramientas
      - homepage.name=Web-Check
      - homepage.icon=https://raw.githubusercontent.com/Lissy93/web-check/1627bed25c46035426570b353c6bbdfc034f4b4d/public/favicon.svg
      - homepage.href=https://webcheck.jaumoso.ovh
      - homepage.description=Analiza cualquier dominio
      - homepage.statusStyle=dot
    networks:
      - dockerproxy

networks:
  dockerproxy:
    external: true
