services:
  dockge:
    image: louislam/dockge:1.4.2
    container_name: dockge
    restart: unless-stopped
    ports:
      - 5002:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/externaldisk0/dockge:/app/data
      - ../:/opt/stacks
    environment:
      # Tell Dockge where to find the stacks
      - DOCKGE_STACKS_DIR=/opt/stacks
networks: {}
