services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
 #     - TZ=Etc/UTC
      - TZ=Europe/Madrid
    volumes:
      - /mnt/externaldisk0/sonarr:/config
      - /mnt/externaldisk0/media/series:/tv #optional
      - /mnt/externaldisk0/media/anime:/anime
      - /mnt/externaldisk0/media/default:/downloads/default #optional
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - jellyfin
      - homarr
networks:
  jellyfin:
    external: true
  homarr:
    external: true
