services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
#      - CLI_ARGS= #optional
      - SETTINGS_ENCRYPTION_KEY=Civera2001%
    volumes:
      - ./config:/config
      - /mnt/externaldisk1/backups:/backups
      - /home/jaumoso:/source
    ports:
      - 8200:8200
    restart: unless-stopped
