services:
  cronmaster:
    image: ghcr.io/fccview/cronmaster:latest
    container_name: cronmaster
    user: root
    ports:
      - 40123:3000
    environment:
      - NODE_ENV=production
      - DOCKER=true
      - NEXT_PUBLIC_CLOCK_UPDATE_INTERVAL=30000
      - AUTH_PASSWORD=${AUTH_PASSWORD}
      - HOST_CRONTAB_USER=root
      - LOCALE=es
      - MAX_LOG_AGE_DAYS=30 # Days to keep logs (default: 30)
      - MAX_LOGS_PER_JOB=50 # Maximum logs per job (default: 50)
      - API_KEY=ohSsPdGADDK0IOQ2vdliE8UCSzZvSpGlufSYD5YECiWqYpLdiwvp4oA2vjb6fGCj
      - LIVE_UPDATES=true
      - APP_URL=https://cron.jaumoso.ovh
    volumes:
      # Docker socket for command execution
      - /var/run/docker.sock:/var/run/docker.sock
      # Data persistence
      - /mnt/externaldisk0/cronmaster/scripts:/app/scripts
      - /mnt/externaldisk0/cronmaster/data:/app/data
      - /mnt/externaldisk0/cronmaster/snippets:/app/snippets
    pid: host
    privileged: true
    restart: unless-stopped
    init: true
networks: {}
