services:
  blinko-website:
    image: blinkospace/blinko:latest
    container_name: blinko-website
    environment:
      NODE_ENV: production
      # NEXTAUTH_URL: http://localhost:1111
      # NEXT_PUBLIC_BASE_URL: http://localhost:1111
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@blinko-postgres:5432/${POSTGRES_USER}
    depends_on:
      postgres:
        condition: service_healthy
      # Make sure you have enough permissions.
    volumes:
      - /mnt/externaldisk0/blinko/app:/app/.blinko
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 1111:1111
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://blinko-website:1111/
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - blinko-network
  postgres:
    image: postgres:14
    container_name: blinko-postgres
    restart: unless-stopped
    ports:
      - 5435:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: Europe/Madrid
      # Persisting container data
      # Make sure you have enough permissions.
    volumes:
      - /mnt/externaldisk0/blinko/db:/var/lib/postgresql/data
    healthcheck:
      test:
        - CMD
        - pg_isready
        - -U
        - ${POSTGRES_USER}
        - -d
        - ${POSTGRES_DB}
      interval: 5s
      timeout: 10s
      retries: 5
    networks:
      - blinko-network
networks:
  blinko-network:
    driver: bridge
