services:
  tududi:
    image: chrisvel/tududi:latest
    container_name: tududi
    environment:
      - TUDUDI_USER_EMAIL=${TUDUDI_USER_EMAIL}
      - TUDUDI_USER_PASSWORD=${TUDUDI_USER_PASSWORD}
      - TUDUDI_SESSION_SECRET=${TUDUDI_SESSION_SECRET}
      - TUDUDI_INTERNAL_SSL_ENABLED=false
      - TUDUDI_ALLOWED_ORIGINS=https://tududi.harambe.ovh,https://tududi.jaumoso.ovh
      #- APP_UID=1000
      #- APP_GID=1000
    volumes:
      - /mnt/externaldisk0/tududi/db:/app/backend/db
    ports:
      - 3049:3002
    restart: unless-stopped
    # Uncomment to run as root for automatic permission fix (not recommended for production)
    #user: 0:0
networks: {}
