version: '3.7'
services:
  fileflows:
    image: revenz/fileflows
    container_name: fileflows
#    runtime: nvidia
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    environment:
      - TZ=Europe/Madrid
      - TempPathHost=/temp
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/docker/fileflows/data:/app/Data
      - /mnt/docker/fileflows/logs:/app/Logs
      - /mnt/docker/fileflows/temp:/temp
    ports:
      - 19200:5000
    restart: unless-stopped
