services:
  composr:
    image: vansmak/composr:latest
    container_name: composr
    ports:
      - "5003:5003"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/jaumoso/selfhosted:/app/projects
      - ./data:/app/data
#      - ./caddy:/caddy_config  # Optional
    environment:
      COMPOSE_DIR: /app/projects
      METADATA_DIR: /app/data
      CONTAINER_METADATA_FILE: /app/data/metadata.json
#      CADDY_CONFIG_DIR: /caddy_config  # Optional
#      CADDY_CONFIG_FILE: Caddyfile     # Optional
#      EXTRA_COMPOSE_DIRS: /path1:/path2:/path3  # Optional
    restart: unless-stopped
