version: '3.3'
services:
    openbooks:
        ports:
            - '5004:80'
        volumes:
            - './booksVolume:/books'
        restart: unless-stopped
        container_name: OpenBooks
        command: --name jaumoso --persist
#        environment:
#          - BASE_PATH=/openbooks/
        image: evanbuss/openbooks:latest

volumes:
    booksVolume:
