services:
    open-archiver:
        image: logiclabshq/open-archiver:latest
        container_name: open-archiver
        restart: unless-stopped
        ports:
            - '4000:4000' # Backend
            - '3238:3000' # Frontend
        env_file:
            - .env
        volumes:
            - /mnt/externaldisk0/open_archiver/archiver-data:/var/data/open-archiver
        depends_on:
            - postgres
            - valkey
            - meilisearch

    postgres:
        image: postgres:17-alpine
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-open_archive}
            POSTGRES_USER: ${POSTGRES_USER:-admin}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
        volumes:
            - /mnt/externaldisk0/open_archiver/pgdata:/var/lib/postgresql/data
        ports:
            - '5432:5432'

    valkey:
        image: valkey/valkey:8-alpine
        container_name: valkey
        restart: unless-stopped
        command: valkey-server --requirepass ${REDIS_PASSWORD}
        ports:
            - '6379:6379'
        volumes:
            - /mnt/externaldisk0/open_archiver/valkeydata:/data

    meilisearch:
        image: getmeili/meilisearch:v1.15
        container_name: meilisearch
        restart: unless-stopped
        environment:
            MEILI_MASTER_KEY: ${MEILI_MASTER_KEY:-aSampleMasterKey}
        ports:
            - '7700:7700'
        volumes:
            - /mnt/externaldisk0/open_archiver/meilidata:/meili_data
