services:
  filebrowser:
    volumes:
      - /home/jaumoso:/home
      # optional if you want db to persist - configure a path under "database" dir in config file.
#      - /mnt/externaldisk0/filebrowser2/database:/home/filebrowser/database
      #- .config.yaml:/home/filebrowser/config.yaml
      # optional mount a temp directory to use. Generally, there is no need for this unless your user is not root or filebrowser.
      # - './tmp/:/home/filebrowser/tmp/'
    ports:
      - 9568:80
    image: gtstef/filebrowser:latest
    # optionally run as non-root filebrowser user
    user: "1000"
    restart: unless-stopped
