services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8097:8096
#    user: jaumoso:jaumoso
    volumes:
      - /mnt/externaldisk0/jellyfin/config:/config
      - /mnt/externaldisk0/jellyfin/cache:/cache
      - type: bind
        source: /mnt/externaldisk0/media
        target: /media
#      - type: bind
#        source: /path/to/media2
#        target: /media2
#        read_only: true
    restart: 'unless-stopped'
    # Optional - alternative address used for autodiscovery
    environment:
      - JELLYFIN_PublishedServerUrl=https://jellyfin.jaumoso.ovh
    # Optional - may be necessary for docker healthcheck to pass if running in host network mode
#    extra_hosts:
#      - 'host.docker.internal:host-gateway'
    networks:
      - jellyfin
      - homarr

networks:
  jellyfin:
    external: true
  homarr:
    external: true
