services:
  farolero:
    image: ghcr.io/jaumoso/farolero:latest
    container_name: farolero
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      # Linux Docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/jaumoso/selfhosted/farolero/config.yaml:/app/config.yaml:ro
      # Path to stacks definitions
      - /home/jaumoso/selfhosted:/stacks:ro

