services:
  mealie:
    container_name: mealie
    image: ghcr.io/mealie-recipes/mealie:latest
    restart: unless-stopped
    volumes:
      - ./mealie-data:/app/data/
    ports:
      - 9091:9000
    environment:
#      PUID: 1000
#      PGID: 1000

      ALLOW_SIGNUP: "true"
      BASE_URL: https://mealie.jaumoso.ovh

      DB_ENGINE: sqlite # Optional: 'sqlite', 'postgres'
      # =====================================
      # Postgres Config
      POSTGRES_USER: mealie
      POSTGRES_PASSWORD: mealie
      POSTGRES_SERVER: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: mealie

      # =====================================
      # Web Concurrency
      WEB_GUNICORN: "false"
      WORKERS_PER_CORE: 0.5
      MAX_WORKERS: 1
      WEB_CONCURRENCY: 1
      # =====================================
      # Email Configuration
      SMTP_HOST:
      SMTP_PORT:
      SMTP_FROM_NAME: Mealie
      SMTP_AUTH_STRATEGY: TLS # Options: 'TLS', 'SSL', 'NONE'
      SMTP_FROM_EMAIL:
      SMTP_USER:
      SMTP_PASSWORD:

volumes:
  mealie-data:
    driver: local
