services:
  ryot-db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - ./postgres_storage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=ryotpostgres
      - POSTGRES_USER=ryotpostgres
      - POSTGRES_DB=ryotpostgres
#      - PUID=1000
#      - PGID=1000
      - TZ=Europe/Madrid
    container_name: ryot-db

  ryot:
    image: "ghcr.io/ignisda/ryot:latest"
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgres://ryotpostgres:ryotpostgres@ryot-db:5432/ryotpostgres
      - VIDEO_GAMES_TWITCH_CLIENT_ID=
      - VIDEO_GAMES_TWITCH_CLIENT_SECRET=
      - FRONTEND_INSECURE_COOKIES=true
      - SERVER_ADMIN_ACCESS_TOKEN=
      - TZ=Europe/Madrid
#      - PUID=1000
#      - PGID=1000
    ports:
      - "5003:8000"
    pull_policy: always
    container_name: ryot
